name: dominoes
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - numpy
  - scipy
  - matplotlib
  - jupyterlab
  - ipympl
  - tqdm
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.7
